### ISSUE TITLE
Switching to UNITY_ANDRIOID option is not respected.

### ISSUE THREAD

**Issue by Legoman99573** [vrchat-community/ClientSim#37]
This prevents testing between platforms if UdonSharp includes this in the code. This would help for testing that udonsharp code works in editor (and yes, this works on pc and quest with no issues when uploaded to VRChat). Though I own a quest for testing, not everyone who creates worlds probably owns a quest headset, which can make debugging pretty annoying.
``` csharp
#if UNITY_ANDROID
            playerReflectionProbe.GetComponent<ReflectionProbe>().cullingMask = probeCullingMaskOverrideQuest;
#elif UNITY_STANDALONE
            playerReflectionProbe.GetComponent<ReflectionProbe>().cullingMask = probeCullingMaskOverride;
#endif
```

**Comment by momo-the-monster** [comment]
Hey @Legoman99573 - thanks for filing an issue, but I cannot reproduce the problem that you're having.

I created a test UdonSharpBehaviour:
```
using UdonSharp;
using UnityEngine;

public class TestAndroid : UdonSharpBehaviour
{
    void Start()
    {
#if UNITY_ANDROID
        Debug.Log($"Hello, Android");
#else
        Debug.Log("Hello, non-Android");
#endif
    }
}
```
I tested this in the Editor under Windows and Android build settings, and the results were as expected. In these screenshots, you can check the difference in the console output against the current platform:

![hello-android](https://user-images.githubusercontent.com/737888/172966009-706ba469-2634-41e8-b158-43c5fe395cec.png)
![hello-non-android](https://user-images.githubusercontent.com/737888/172966010-aeff85f9-9cd7-4dd6-8fab-d9050f5bb50d.png)

Note that I did press "Compile All UdonSharp Programs" after switching platforms in order to recompile the program with the Android guards in place. If that step is what tripped you up, you can [file an issue on the UdonSharp repo](https://github.com/vrchat-community/UdonSharp/issues) to suggest this happen automatically when a user changes the active build platform.

**Comment by Legoman99573** [comment]
Thank you. I will open one there for sure as it can cause unintended behavior like something needing to run on UNITY_ANDROID for optimization reasons.
