### ISSUE TITLE
Game window doesn't capture mouse if controller is connected

### ISSUE THREAD

**Issue by Okabintaro** [vrchat-community/ClientSim#40]
When using ClientSim together with a connected controller it can happen that the game window doesn't grab the focus, even when clicked.

I was basically stuck at this screen and couldn't do anything: ![Stuck](https://cdn.discordapp.com/attachments/773410094624669708/996110895254077571/unknown.png)

As soon as I disconnected it, everything works fine.
For reference: I was using a DualSense(PS5) Controller connected via USB.

**Comment by momo-the-monster** [comment]
This is due to the PS5 DualSense Controller [not being supported by version of the Unity InputSystem we're using](https://issuetracker.unity3d.com/issues/input-system-ps5-controller-is-not-supported-on-desktop-platforms-and-in-editor) (1.0.2 - the last version verified to work with 2019.4).

I was able to reproduce the issue _and_ verify that it is solved by updating the package to 1.2.0 using the Unity Package Manager - but this could have side-effects. We've reached out to Unity to discuss whether there are any known issues with using this version in 2019.4.31f1, and we'll evaluate it ourselves to see if we notice any differences.
