### ISSUE TITLE
Unecessary message in DisplayInitialPageForPlayer

### ISSUE THREAD

**Issue by Fairpl3x** [vrchat-community/ClientSim#62]
ClientSimDisplayedPage.PAUSE_MENU
ClientSimDisplayedPage.WARNING_PAGE

Those menus are not necessary and we should be able to be disable them from the clientSim settings. It's quite annoying to have to see them every time we enter play mode.

**Comment by cubedparadox** [comment]
We've discussed this issue internally, and this behavior is working as intended.
We only show the initial warning about differences once per editor session, to ensure users have a reminder about it. We need to show the Pause Menu when users enter Play Mode, in order to ensure that they always click into the Game View window, which is necessary for capturing mouse input in a non-intrusive way (this is the same as when you hit escape and have to click back into the window to close the pause menu).
